
### Data manipulation and analysis with Pandas 
means using Python’s Pandas library to clean, organize, modify, and understand data. Pandas helps us read data from files like CSV, select rows and columns, handle missing values, sort data, filter records, and calculate useful information such as averages and totals. It makes working with large datasets easier and faster.

In [6]:

### reading csv file and apply some method

import pandas as pd

df = pd.read_csv("sales.csv")

print("First Five Row :\n")
print(df.head(5))
print()
print("Last Five Row : \n")
print(df.tail(5))

First Five Row :

  Sale_ID        Date    Product  Quantity  Unit_Price  Total_Sales
0       1  2026-08-01     Laptop       2.0       85000     170000.0
1       2  2026-08-01      Mouse       5.0        1500       7500.0
2       3  2026-08-01   Keyboard       3.0        3500      10500.0
3       4  2026-08-02    Monitor       NaN       28000      56000.0
4       6  2026-08-02  USB Cable      10.0         500       5000.0

Last Five Row :

   Sale_ID        Date       Product  Quantity  Unit_Price  Total_Sales
17      16  2026-08-06        Laptop       1.0       85000      85000.0
18      17  2026-08-06        Webcam       3.0        6500      19500.0
19      18  2026-08-07           SSD       2.0        9500      19000.0
20      19  2026-08-07       Printer       2.0       22000      44000.0
21      20  2026-08-08  Laptop Stand    3200.0       12800          NaN

In [ ]:

#  Data type of table and describe() method 

print("Describe about table : \n")
print(df.describe())
print("\nData type of Table column : \n")
df.dtypes

Describe about table :

       Quantity    Unit_Price
count    8.0000      8.000000
mean     5.5000  14275.000000
std      4.6291  28716.682558
min      2.0000    500.000000
25%      2.7500   2775.000000
50%      3.5000   4000.000000
75%      6.2500   7250.000000
max     15.0000  85000.000000

Data type of Table column :

Product        object
Category       object
Quantity      float64
Unit_Price    float64
Sale_Date      object
Pay_Method     object
dtype: object

In [17]:

#  managing missing value in table 

# showing table where null value is present 
print(df.isnull())

print()
# showing null in table column 
print(df.isnull().any())

print()
# counting no.of null value in column:
print(df.isnull().sum())

   Product  Category  Quantity  Unit_Price  Sale_Date  Pay_Method
0    False     False     False       False      False       False
1    False     False     False       False      False       False
2    False     False      True       False       True       False
3    False     False     False        True      False        True
4    False      True     False       False      False       False
5    False     False      True       False      False       False
6    False     False     False        True      False       False
7    False     False     False       False       True       False
8    False     False     False       False      False        True
9    False      True     False       False      False       False

Product       False
Category       True
Quantity       True
Unit_Price     True
Sale_Date      True
Pay_Method     True
dtype: bool

Product       0
Category      2
Quantity      2
Unit_Price    2
Sale_Date     2
Pay_Method    2
dtype: int64

In [49]:

#  filling the missing value  with zero 0

null_fill = df.fillna(0)

# filling the missing value with mean() with the new column

df['New_Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

df['New_Unit_Price'] = df['Unit_Price'].fillna(df['Unit_Price'].mean())


print(df.head(6))

        Items     Category  Quantity  Unit_Price   Sale_Date Pay_Method  \
0      Laptop  Electronics       2.0     85000.0  2026-08-01       Cash
1       Mouse  Accessories      10.0      1500.0  2026-08-01       Card
2    Keyboard  Accessories       NaN      3500.0         NaN     Online
3     Monitor  Electronics       3.0         NaN  2026-08-02        NaN
4  Headphones          NaN       5.0      4500.0  2026-08-03       Card
5      Webcam  Electronics       NaN      6500.0  2026-08-03     Online

   New_Quantity  New_Unit_Price
0           2.0         85000.0
1          10.0          1500.0
2           5.5          3500.0
3           3.0         14275.0
4           5.0          4500.0
5           5.5          6500.0

In [51]:

df.drop('New_Quantity',axis=1,inplace=True)
df.drop('New_Unit_Price',axis=1,inplace=True)

In [ ]:

## replacing column name

df =df.rename(columns={'Product':'Items'})
df.head(3)

#  syntax : (columns :{'col_name':'new_col_name'})

      Items     Category  Quantity  Unit_Price   Sale_Date Pay_Method
0    Laptop  Electronics       2.0     85000.0  2026-08-01       Cash
1     Mouse  Accessories      10.0      1500.0  2026-08-01       Card
2  Keyboard  Accessories       NaN      3500.0         NaN     Online

In [72]:
## changing the data types of column

df['New_Quantity'] = df['Quantity'].fillna(df['Quantity'].mean()).astype(int)
df.head(3)

# note -- changing data type with using(.astype(int,float))
# note -- if there is null then it show error

,Items,Category,Quantity,Unit_Price,Sale_Date,Pay_Method,New_Quantity
0,Laptop,Electronics,4.0,85000.0,2026-08-01,Cash,4
1,Mouse,Accessories,20.0,1500.0,2026-08-01,Card,20
2,Keyboard,Accessories,NaN,3500.0,NaN,Online,11

In [ ]:

# Data Aggrigate and grouping
# grouping the items values 

groupby_c= df.groupby('Category')['Quantity'].mean()
print(groupby_c)


# syntax : df.groupby('Column_name')['value_column'].function

Category
Accessories    12.500000
Electronics     2.333333
Storage         4.000000
Name: Quantity, dtype: float64

In [ ]:

# grouping by the two object

group_c_i = df.groupby(['Category','Items'])['Quantity'].sum()
print(group_c_i)
print()
group_c_i = df.groupby(['Category','Items'])['Quantity'].mean()
print(group_c_i)


# note  --- (['First_column','Second_column'])['Value_column'].Function()

Category     Items
Accessories  Keyboard      0.0
             Mouse        10.0
             USB Cable    15.0
Electronics  Laptop        2.0
             Monitor       3.0
             Printer       2.0
             Webcam        0.0
Storage      SSD           4.0
Name: Quantity, dtype: float64

Category     Items
Accessories  Keyboard      NaN
             Mouse        10.0
             USB Cable    15.0
Electronics  Laptop        2.0
             Monitor       3.0
             Printer       2.0
             Webcam        NaN
Storage      SSD           4.0
Name: Quantity, dtype: float64

In [ ]:

# using muliple arrggiate function 

groupby_arg = df.groupby('Category')['Quantity'].agg(['sum','mean','count'])
print(groupby_arg)

# note -- some of the .agg(['sum',;......,'..'])

              sum       mean  count
Category
Accessories  25.0  12.500000      2
Electronics   7.0   2.333333      3
Storage       4.0   4.000000      1

In [ ]:

# apply the function in data frame column

df['New_Quantity']=df['Quantity'].fillna(df['Quantity'].mean()).astype(int).apply(lambda x :x*2)
df.head(3)


# note -- changing one dataype column to another data type (.astype(data type))
# note -- if there is null in column then function cannot be apply

,Items,Category,Quantity,Unit_Price,Sale_Date,Pay_Method,New_Quantity
0,Laptop,Electronics,4.0,85000.0,2026-08-01,Cash,8
1,Mouse,Accessories,20.0,1500.0,2026-08-01,Card,40
2,Keyboard,Accessories,NaN,3500.0,NaN,Online,22

In [84]:

## merging two dataframe 

df1 = pd.DataFrame({'key':['A','B','C'],'value_1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'],'value_2':[3,4,5]})

print(pd.merge(df1,df2,on='key',how='left'))

# how == inner(come),outer(all),left(a-b),right(b-a)

  key  value_1  value_2
0   A        1      3.0
1   B        2      4.0
2   C        3      NaN


### Reading data from the various source using pandas

 StringIO is used to treat a string like a file.
 This is useful because pd.read_json() can read JSON from a file-like object.
 Your JSON contains multiple lines, so triple quotes allow you to write it across several lines.

In [ ]:

import pandas as pd

from io import StringIO


data = '''{
    "Employe_Name":"Sabin Rai",
    "Email":"raisabin@gmail.com",
    "Profile":[{"title_1":"Team Leader","title_2":"Developer"}]}'''

rd = pd.read_json(StringIO(data))
rd

,Employe_Name,Email,Profile
0,Sabin Rai,raisabin@gmail.com,"{'title_1': 'Team Leader', 'title_2': 'Develop..."

In [ ]:
# again changing into json

print(rd.to_json())
print()
# with index default and it became the key
print(rd.to_json(orient='index'))
print()
# with orient = records and it show the data as object
print(rd.to_json(orient='records'))

{"Employe_Name":{"0":"Sabin Rai"},"Email":{"0":"raisabin@gmail.com"},"Profile":{"0":{"title_1":"Team Leader","title_2":"Developer"}}}

{"0":{"Employe_Name":"Sabin Rai","Email":"raisabin@gmail.com","Profile":{"title_1":"Team Leader","title_2":"Developer"}}}

[{"Employe_Name":"Sabin Rai","Email":"raisabin@gmail.com","Profile":{"title_1":"Team Leader","title_2":"Developer"}}]

In [27]:
# reading through the link 

df = pd.read_csv("https://raw.githubusercontent.com/reisanar/datasets/master/Advertising.csv",header=None)
df.head(2)

# without header 

df = pd.read_csv("https://raw.githubusercontent.com/reisanar/datasets/master/Advertising.csv")
df.head(2)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4

In [29]:

#  again converting link into csv file

df.to_csv("New_records.csv")

Collecting lxml
  Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------------ --------------------- 1.8/4.0 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 11.5 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

In [2]:

## reading html.file data

import pandas as pd

url = 'https://opensource.adobe.com/Spry/articles/html_dataset/index.html'

new_df =pd.read_html(url)
print(new_df[0])
print()
print(new_df[2])

#  note --- [..] help to read the table from html page one by one

  first name last name username           phone
0       Kirk     Davis   kdavis  (415) 333-4334
1      James    Miller  jmiller  (415) 333-7566
2       Alex    Wilson  awilson  (415) 333-9843
3     Albert     Moore   amoore  (415) 333-7584

          0   1   2   3
0   January  35  74  34
1  February  23  57  44
2     March  28  37  55

In [ ]:

## Another Example html_file

url = "https://raw.githubusercontent.com/ebabel/HTMLTables/master/test.html"
code= pd.read_html(url,match="country",header=0)[0]

In [10]:

#  reading excel file

ex_df =pd.read_excel("data.xlsx")
ex_df

         Name  Age
0   Sabin Rai   22
1   Susan Rai   23
2   Ankit Rai   22
3  Yogesh Rai   30

In [13]:

#  working with pickles file
ex_df.to_pickle('mydata')

# reading from the pickles file

pd.read_pickle("mydata")

         Name  Age
0   Sabin Rai   22
1   Susan Rai   23
2   Ankit Rai   22
3  Yogesh Rai   30